server:
  port: 10002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: backup
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://master:10001/eureka/
  server:
    enable-self-preservation: false