server:
  port: 10041
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
zuul:
  routes:
    api-a:
      path:
        /api-a/**
      service-id:
        ribbon-server
    api-b:
      path:
         /api-b/**
      service-id:
        feign-server