server:
  port: 10001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://backup:10002/eureka/